name: language_app
description: "Mobile app for the championship."
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/illustrations/firstIllustration.svg
    - assets/illustrations/secondIllustration.svg
    - assets/illustrations/thirdIllustration.svg

  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-Bold.ttf
          weight: 700
        - asset: assets/fonts/Fredoka-Light.ttf
          weight: 300
        - asset: assets/fonts/Fredoka-Medium.ttf
          weight: 500
        - asset: assets/fonts/Fredoka-Regular.ttf
          weight: 400
        - asset: assets/fonts/Fredoka-SemiBold.ttf
          weight: 600
